In [2]:
import numpy as np


In [5]:
num_exp = 4
num_act = 1
lr = 0.02
seed = 0
#/home/ubuntu/MuP_MOE/run_data/mutransfer_lr_cccc/out_20250909_164542/width512_depth14_experts4_active1_seed0_lr0.02/router_weights_iter_1.npy
for iter_idx in range(5):
    ind = 1000 * iter_idx + 1
    file_path = f"/home/ubuntu/MuP_MOE/run_data/mutransfer_lr_cccc/out_20250909_164542/width512_depth14_experts{num_exp}_active{num_act}_seed{seed}_lr{lr}/router_weights_iter_{ind}.npy"
    router_weights = np.load(file_path)
    print()
    print(np.linalg.svd(router_weights[0])[1])
    print(np.linalg.svd(router_weights[6])[1])
    print(np.linalg.svd(router_weights[-1])[1])
    print()


[0.49042705 0.47015992 0.44965148 0.43228066]
[0.5101305  0.4737925  0.4506966  0.43486714]
[0.46686944 0.4477416  0.4462801  0.4221918 ]


[0.48892447 0.46871755 0.44827226 0.43095466]
[0.50856584 0.47233942 0.4493133  0.43353316]
[0.46540707 0.44637057 0.44491294 0.42089742]


[0.48444313 0.46441928 0.44416404 0.4270035 ]
[0.50390875 0.46800828 0.44517303 0.42955318]
[0.46117377 0.44227925 0.44083226 0.41703412]


[0.4787447  0.45895436 0.43894172 0.42197874]
[0.498003   0.4624409  0.43993667 0.42447326]
[0.4569447  0.43741572 0.43500617 0.41205138]


[0.47353727 0.45395318 0.43415606 0.41737407]
[0.49448127 0.45754698 0.43691465 0.42032313]
[0.45387024 0.44301477 0.43219137 0.40677553]

